// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: log_pipelines.sql

package model

import (
	"context"
)

const listLogPipelines = `-- name: ListLogPipelines :many
SELECT id, name, source, parsers, created_at, updated_at, deleted_at FROM log_pipelines
ORDER BY id
`

func (q *Queries) ListLogPipelines(ctx context.Context) ([]LogPipeline, error) {
	rows, err := q.db.Query(ctx, listLogPipelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogPipeline
	for rows.Next() {
		var i LogPipeline
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Source,
			&i.Parsers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
