// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type LogPipeline struct {
	ID        pgtype.UUID
	Name      string
	Source    string
	Parsers   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Policy struct {
	ID        pgtype.UUID
	Name      string
	Path      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
