// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: policies.sql

package model

import (
	"context"
)

const listPolicies = `-- name: ListPolicies :many
SELECT id, name, path, created_at, updated_at, deleted_at FROM policies
ORDER BY id
`

func (q *Queries) ListPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
